speakers2015:
  - first_name: "Introduction by Professor Andrew Hamilton, FRS"
    last_name: ""
    email: ""
    link: ""
    position: "Vice-Chancellor"
    dept: "University of Oxford"
    research_interests: ""
    talk_title: ""
    talk_order: 1

  - first_name: Chas
    last_name: Bountra
    email: ""
    link: ""
    position: "Professor of Translational Medicine"
    dept: "SGC"
    research_interests: "Using X ray structures of novel human proteins to generate small molecule inhibitors, screening in human cells to identify novel targets for drug discovery, and then developing clinical candidates for evaluation in patients."
    talk_title: ""
    talk_order: 2

  - first_name: Tom
    last_name: Brown
    email: ""
    link: ""
    position: "Professor of Nucleic Acid Chemistry"
    dept: "Department of Chemistry"
    research_interests: "Nucleic acid chemistry, DNA sequence recognition and application of nucleic acids to nanotechnology, diagnostics and biology."
    talk_title: ""
    talk_order: 3

  - first_name: Ian
    last_name: Churcher
    email: ""
    link: ""
    position: ""
    dept: "GlaxoSmithKline"
    research_interests: ""
    talk_title: ""
    talk_order: 4

  - first_name: Daniel
    last_name: Ebner
    email: ""
    link: ""
    position: "Operational Cell Screening Officer"
    dept: "Target Discovery Institute"
    research_interests: "Phenotypic screening and the UK National Phenotypic Screening Centre."
    talk_title: ""
    talk_order: 5

  - first_name: Christian
    last_name: Eggeling
    email: ""
    link: ""
    position: "Professor of Molecular Immunology"
    dept: "Weatherall Institute of Molecular Medicine"
    research_interests: "The Eggeling laboratory focuses on the application and development of advanced ultra-sensitive, live-cell fluorescence microscopy techniques, such as optical super-resolution microscopy or nanoscopy featuring a spatial resolution down to the molecular level, superior to conventional optical microscopes. These super-resolution microscopes are optimized and used to unravel nanoscopic changes at the molecular level in living cells following cellular immune responses, such as T-cell activation."
    talk_title: ""
    talk_order: 6

  - first_name: Christophe
    last_name: Genicot
    email: ""
    link: ""
    position: "Senior Director, Global Chemistry"
    dept: "UCB"
    research_interests: ""
    talk_title: ""
    talk_order: 7

  - first_name: David R.
    last_name: Greaves
    email: ""
    link: ""
    position: "Professor of Inflammation Biology"
    dept: "Sir William Dunn School of Pathology"
    research_interests: "My lab studies the role of monocytes and macrophages in the initiation and resolution of chronic inflammation. We are particularly interested in the role chemokines and other chemoattractants play in atherosclerosis - a disease process in arteries that leads to angina, heart attacks and strokes."
    talk_title: ""
    talk_order: 8

  - first_name: Geoff
    last_name: Higgins
    email: ""
    link: ""
    position: "Cancer Research UK Clinician Scientist"
    dept: "Department of Oncology"
    research_interests: "Laboratory and clinical research to better understand the molecular basis of tumour cell resistance to radiation treatment with the long term aim of developing treatments to make radiotherapy more effective."
    talk_title: ""
    talk_order: 9

  - first_name: Simon
    last_name: Lovestone
    email: ""
    link: ""
    position: "Professor of Translational Neuroscience"
    dept: "Department of Psychiatry"
    research_interests: "Seeking new targets for therapy in Alzheimer's disease by understanding basic mechanisms, in disease modification trials and experimental medicine and in the search for biomarkers for early diagnosis."
    talk_title: ""
    talk_order: 10

  - first_name: Frances
    last_name: Platt
    email: ""
    link: ""
    position: "Professor of Biochemistry and Pharmacology"
    dept: "Department of Pharmacology"
    research_interests: "Identifying drugs to target steps in the pathogenic cascade of lysosomal disorders, and testing them as mono-therapies or in combination with other therapies. Evaluating these in a pre-clinical setting before conducting translational studies in patients with clinical collaborators."
    talk_title: ""
    talk_order: 11

  - first_name: Angela
    last_name: Russell
    email: ""
    link: ""
    position: "RCUK Fellow in Medicinal Chemistry"
    dept: "Department of Chemistry"
    research_interests: "Developing small molecule modulators to study developmental signalling pathways, e.g. Hedgehog, Wnt/wingless and Bone Morphogenetic Protein. Developing inhibitors to target challenging proteins, e.g. phosphatases or proteins where a physiological role is not clearly defined, e.g. acetyl transferases. Developing new techniques and methodologies for compound library design and synthesis."
    talk_title: ""
    talk_order: 12

  - first_name: Kevin
    last_name: Talbot
    email: ""
    link: ""
    position: "Professor of Translational Neuroscience"
    dept: "Nuffield Department of Clinical Neuroscience"
    research_interests: "Identifying the earliest pathological pathways activated in motor neuron disease in order to define the most therapeutically tractable areas for drug therapy and to apply these findings to clinical studies in patients."
    talk_title: ""
    talk_order: 13

  - first_name: Richard
    last_name: "Wade-Martins"
    email: ""
    link: ""
    position: "Associate Professor of Biomedical Science"
    dept: "Department of Physiology, Anatomy and Genetics"
    research_interests: "Understanding molecular mechanisms of age-related neurodegenerative diseases to generate novel molecular therapies."
    talk_title: ""
    talk_order: 14

  - first_name: Cathy
    last_name: Ye
    email: ""
    link: ""
    position: "Associate Professor in Engineering Science"
    dept: "Department of Engineering Science"
    research_interests: "Stem cell technologies and stem cell based screening platforms."
    talk_title: ""
    talk_order: 15

symp2015:  
  title: Current expertise and future directions in drug discovery
  overview:
    - paragraph: "This event showcases top chemical biology research from labs at Oxford.  Particular emphasis is placed on linking basic chemical biology research to work in the clinic."
      order: 1

    - paragraph: "The first session of the day looks at disease-agnostic technologies to aid drug discovery. The second session features work on targets and pathways applied to a variety of illnesses. The third session focuses on therapeutic interventions for neurodegenerative diseases."
      order: 2

    - paragraph: "Each session features top-class science presentations from a broad range of Oxford’s biomedical and physical science departments, with speakers from industry giving their perspective throughout the day. This sets the stage for a round-table discussion between opinion leaders from across Oxford and industry. The conversation will focus on how we can best work together to translate ideas into new medicines."
      order: 3

    - paragraph: "The symposium will bring together 200 delegates including Oxford researchers, industry colleagues and technology transfer professionals. In doing so, it will provide the ideal forum for discussion and lead to lasting collaborative relationships."
      order: 4

    - paragraph: "Networking breaks and poster sessions will allow discussion to continue outside of the lecture theatre. The day will finish with a wine reception in the common room of the Andrew Wiles building, which provides a beautiful view of the 18th century Radcliffe Observatory."
      order: 5
  programme_intro: "We are finalising the agenda and will publish it here on Wednesday 15th April. On the day, coffee will be served from 9am at the Andrew Wiles Building. Andrew Hamilton (Vice Chancellor of the University of Oxford) will open the event at 9.30am. The evening wine reception will finish at 7pm."
  why_attend:
    - picture_url: "discover-telescope.png"
      caption_header: "Discover"
      caption_text: "cutting-edge chemical biology from Oxford"
      category: "industry"
    - picture_url: "link-chain.png"
      caption_header: "Link"
      caption_text: "with people at Oxford who can make collaboration happen"
      category: "industry"
    - picture_url: "network-atom.png"
      caption_header: "Network"
      caption_text: "with industry to maximise the impact of your science"
      category: "oxford"
    - picture_url: "connect-bridge.png"
      caption_header: "Connect"
      caption_text: "with colleagues across Oxford departments"
      category: "oxford"
  banners:
    - message_text: "Industry Early Bird Registration"
      date_start: "2015-03-01"
      date_end: "2015-04-01"
      button_text: "Open Now"
      banner_class: "success"
      button_link: "https://www.eventbrite.co.uk/e/current-expertise-and-future-directions-in-drug-discovery-an-oxford-industry-conversation-tickets-15943271755"

    - message_text: "Official registration opens Tuesday 31st March 2015"
      date_start: "2015-03-01"
      date_end: "2015-04-01"
      button_text: "Set Reminder"
      banner_class: "info"
      button_link: "/assets/files/conversation-2015-regopen.ics"

    - message_text: "Registration for Industry and Oxford PIs"
      date_start: "2015-03-31"
      date_end: "2015-04-30"
      button_text: "Open Now"
      banner_class: "success"
      button_link: ""

    - message_text: "Registration for Oxford post-docs and research assistants opens 30th April 2015"
      date_start: "2015-03-31"
      date_end: "2015-04-30"
      button_text: "Set Reminder"
      banner_class: "info"
      button_link: ""

    - message_text: "Registration for Oxford students opens 31st May 2015"
      date_start: "2015-03-31"
      date_end: "2015-06-01"
      button_text: "Set Reminder"
      banner_class: "info"
      button_link: ""

    - message_text: "Registration for Industry, Oxford PIs, Oxford research assistants"
      date_start: "2015-03-31"
      date_end: "2015-06-01"
      button_text: "Open Now"
      banner_class: "success"
      button_link: ""

    - message_text: "Registration for Industry and Oxford"
      date_start: "2015-05-31"
      date_end: "2015-07-01"
      button_text: "Open Now"
      banner_class: "info"
      button_link: ""

