authors:
  paul:
    display_name: Paul Barrett
    email: paul.barrett@chembiohub.ox.ac.uk
    github: paulbarrett79
  michael:
    display_name: Michael O'Hagan
    email: michael.ohagan@chembiohub.ox.ac.uk
    github: michaelohagan
  karen:
    display_name: Karen Porter
    email: karen.porter@chembiohub.ox.ac.uk
    github: karenporter
  andy:
    display_name: Andrew Stretton
    email: andrew.stretton@chembiohub.ox.ac.uk
    github: strets123
  anthony:
    display_name: Anthony Bradley
    email: oommppaa.help@gmail.com
    github: abradle
  adam:
    display_name: Adam Hendry
    email: adam.hendry@chembiohub.ox.ac.uk
    github: aekhendry
  oakley:
    display_name: Oakley Cox
    email: oakley.cox@keble.ox.ac.uk
    github: ""

name: Chembio Hub Blog
title: ChemBio Hub Website
description: A team blog about the technology and stories behind the chembio hub project
url: https://chembiohub.ox.ac.uk
non_https_url: http://chembiohub.ox.ac.uk

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
        - "/blog/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

excerpt_separator: "<!-- more -->"
permalink: /blog/:year/:month/:day/:title.html

events:
  - title: "Chemical biology across the University of Oxford"
    subtitle: "A symposium by ChemBio Hub to strengthen interdepartmental research connections"
    date_start: "2014-11-10"
    date_end: "2014-11-10"
    link: "/symposium2014"

  - title: "Current expertise and future directions in drug discovery"
    subtitle: "An Oxford-Industry conversation"
    date_start: "2015-07-31"
    date_end: "2015-07-31"
    link: "/conversation"


