authors:
  paul:
    display_name: Paul Barrett
    email: paul.barrett@sgc.ox.ac.uk
    github: paulbarrett79
  michael:
    display_name: Michael O'Hagan
    email: michael@chembiohub.ox.ac.uk
    github: michaelohagan
  karen:
    display_name: Karen Porter
    email: karen@chembiohub.ox.ac.uk
    github: karenporter
  andy:
    display_name: Andrew Stretton
    email: andrew@chembiohub.ox.ac.uk
    github: strets123
  anthony:
    display_name: Anthony Bradley
    email: oommppaa.help@gmail.com
    github: abradle

name: Chembio Hub Blog
description: A team blog about the technology and stories behind the chembio hub project
url: http//chembiohub.ox.ac.uk

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
        - "/blog/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

excerpt_separator: "<!-- more -->"
permalink: /blog/:year/:month/:day/:title.html
